parameters:
#    web_student_entreprise.example.class: webStudent\EntrepriseBundle\Example

services:
#    web_student_entreprise.example:
#        class: %web_student_entreprise.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
